#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Check for root
if (( $EUID != 0 )); then
  printf "${RED}Please run as root/sudo${NC}\n"
  exit
fi

# Install
printf "Create /etc/onmac\n"
mkdir /etc/onmac

printf "Copying default config to /etc/onmac/knownmacs.conf\n"
cp ./knownmacs.conf /etc/onmac/knownmacs.conf

printf "Copying onmac to /usr/local/bin/onmac\n"
cp ./onmac /usr/local/bin/onmac

printf "${GREEN}Done.${NC}\n"
printf "Edit /etc/onmac/knownmacs.conf to configure your mac list\n"
