#!/bin/bash


#param 1:subnet

#scan network with params
noutput=$(nmap -sP $1 | tr '\n' ' ' | cut -c 2-)

#get ip and mac from output
iplist=$(echo $noutput | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
maclist=$(echo $noutput | grep -E -o '[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}')

#Turn lists into arrays
macarray=( $maclist )
iparray=( $iplist )

#matching
unknowncount=0 #var that will store how many unmatched mac addresses have been found
unknown=() #unknow devices array
for i in "${!macarray[@]}" #loop through macs
do
	case "${macarray[i]}" in

		#match know macs
		
		####DEV####

		#mac not found = add to unknown count and add its data to array
		*)
			(( unknowncount++ ))
			unknown+=('ip: '${iparray[i]}' mac: '${macarray[i]})
		;;
	esac
done
echo "$unknowncount unknown devices are online." #output unknown count
for i in "${!unknown[@]}" #loop through unknowns
do
	echo "${unknown[i]}"
done
